Visual tweaks from vojta
eggheadio/egghead-articles pull request #12
Opened 2017-11-25 17:53 UTC by AkashGutha

2018-01-23 17:09 UTC, tayiorbeii requested changes
There are some `no-unused-vars` warnings when running locally. 

The vertical edges of the logo icon are cut off a bit: https://cl.ly/1S040w183I22

The search button on the article detail page isn't centered quite right: https://cl.ly/2N1w2x1I1h0I

Also, I'm thinking that the article URLs with the big long UUIDs are temporary, but just pointing them out :)

2018-01-23 17:09 UTC, tayiorbeii commented on src/Components/PricingTierCard.js
> +            <p className={css({ fontSize: "15px" })}>usually 299,99$</p>
`.` instead of `,` for the price?

2018-01-23 17:09 UTC, tayiorbeii commented on src/Pages/LandingPage.js
>        console.log("I will re-render, since the observables changed!");
remove log

2018-01-23 17:09 UTC, tayiorbeii commented on src/Pages/LandingPage.js
> +      console.log("dimensions updated");
remove log

2018-01-23 17:09 UTC, tayiorbeii commented on src/Pages/LandingPage.js
> +      console.log(this.state);
remove log

2018-01-23 17:32 UTC, AkashGutha commented on src/Components/PricingTierCard.js
> +            <p className={css({ fontSize: "15px" })}>usually 299,99$</p>
new `pricing page` is up so nothing to bother about this.

2018-02-05 19:07 UTC, merged

2018-02-12 22:55 UTC, tayiorbeii commented
👍